create user test identified by test;


  CREATE TABLE "TEST"."DEVICE_CARD" 
   (	"SIM_ID" NUMBER NOT NULL ENABLE, 
	"OPERATOR_CODE" NUMBER NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	 CONSTRAINT "DEVICE_PK" PRIMARY KEY ("SIM_ID", "OPERATOR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
CREATE SEQUENCE TEST.SIM_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1;

INSERT INTO "TEST"."DEVICE_CARD" (SIM_ID, OPERATOR_CODE, COUNTRY, STATUS) VALUES ('1', '1', 'Italy', 'READY');
INSERT INTO "TEST"."DEVICE_CARD" (SIM_ID, OPERATOR_CODE, COUNTRY, STATUS) VALUES ('2', '12', 'Italy', 'ACTIVE');
INSERT INTO "TEST"."DEVICE_CARD" (SIM_ID, OPERATOR_CODE, COUNTRY, STATUS) VALUES ('3', '123', 'Italy', 'WAITING_FOR_ACTIVATION');
INSERT INTO "TEST"."DEVICE_CARD" (SIM_ID, OPERATOR_CODE, COUNTRY, STATUS) VALUES ('4', '1234', 'Italy', 'BLOCKED');
INSERT INTO "TEST"."DEVICE_CARD" (SIM_ID, OPERATOR_CODE, COUNTRY, STATUS) VALUES ('5', '12345', 'Italy', 'DEACTIVATED');
